# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 940aaa6965d9f87cc2a019169ca14c1cce512da6c6a469ae85a454cfbf479265678a93996f43079febde870e3b57f0d5ad7d313ff8161e9845968eecf895c8c4

test:
  secret_key_base: 3f9c53ea04969809b3ce982c04441d8ecd2f6203eb7017de017319001b195a676901a75d63a1798d6937046558b7688e958569f459d7ca7a025d9942b060cd01

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
